### ISSUE TITLE
`TypeError: handle is undefined` when rapidly updating

### ISSUE THREAD

**Issue by laurin** [konvajs/svelte-konva#130]
I am working on a project where I am updating `svelte-konva` Elements quite frequently. 
Sometimes `svelte-konva` throws the following error. 

```
Uncaught (in promise) TypeError: handle is undefined
    update Circle.svelte:30
    update scheduler.js:115
    flush scheduler.js:79
    promise callback*schedule_update scheduler.js:20
    make_dirty Component.js:81
    ctx Component.js:129
    instance ble-trilateration.svelte:1153
    handleMessage mqtt-client.ts:56
    connect mqtt-client.ts:69
    emit events.js:153
    handlePublish publish.ts:172
    handle index.ts:29
    work client.ts:725
    _write client.ts:749
    writeOrBuffer writable.js:334
    _write writable.js:283
    write writable.js:286
    ondata _stream_readable.js:629
    emit events.js:153
    addChunk _stream_readable.js:279
    readableAddChunk _stream_readable.js:262
    push _stream_readable.js:228
    _forward index.js:172
    onreadable index.js:136
    emit events.js:153
    emitReadable_ readable.js:509
    run browser.js:153
    drainQueue browser.js:123
    setTimeout handler*runTimeout browser.js:41
    nextTick browser.js:143
    emitReadable readable.js:502
    addChunk readable.js:284
    readableAddChunk readable.js:255
    push readable.js:201
    onMessage ws.ts:231
```

This seems to be caused by `handle` not always being defined, but nevertheless being used for setting the config attributes when the config changes.  
See https://github.com/konvajs/svelte-konva/blob/bf8b5a9e4cea32ba6eb3f453ca4d146d759d9846/src/lib/Circle.svelte#L38C29-L38C29

Unfortunately I cannot provide a minimal reproducible example right now, hopefully later.

**Comment by TeyKey1** [comment]
Hi @laurin 

Thank you for pointing out this issue. I've just had a quick glance at the `Circle.svelte` code, but I currently don't see how it can become undefined during the lifetime of a component instance. Are you perhaps manipulating the handle from outside the component in a way that could make it undefined?

I can take a better look at this by the end of this week. However, it would make my life easier if you could describe what you are trying to accomplish, so I can try to reproduce this. A minimal repro would be even better.

**Comment by TeyKey1** [comment]
#136 is now merged which prevents the user from overwriting the internal handle of the component resulting in behavior as described in this issue. Technically, the library user can still overwrite the handle from outside the component, but it will not affect any component internals but may still result in wrong behavior outside the component. Generally it is considered a responsibility of the user to avoid overwriting the handle as it is meant to be read-only. This can not be expressed in svelte right now as a compile-time check, and I don't think it warrants a runtime check.

I'm quite sure this issue is caused by overwriting the handle in some way. I currently don't see any way this could be caused by the library in any way. In case you have more info on the use-case or even a repro, feel free to reopen the issue and I will take a look at it. Without any further information, I cannot really help you with this issue.
